/*
 * Tracealyzer J-Link RTT stream-port configuration.
 */
#ifndef TRC_STREAM_PORT_CONFIG_H
#define TRC_STREAM_PORT_CONFIG_H

#ifdef __cplusplus
extern "C" {
#endif

#define TRC_CFG_STREAM_PORT_USE_INTERNAL_BUFFER 0
#define TRC_CFG_STREAM_PORT_INTERNAL_BUFFER_SIZE 5120
#define TRC_CFG_STREAM_PORT_INTERNAL_BUFFER_TRANSFER_MODE TRC_INTERNAL_EVENT_BUFFER_OPTION_TRANSFER_MODE_ALL
#define TRC_CFG_STREAM_PORT_INTERNAL_BUFFER_CHUNK_SIZE 1024
#define TRC_CFG_STREAM_PORT_INTERNAL_BUFFER_CHUNK_TRANSFER_AGAIN_SIZE_LIMIT 256
#define TRC_CFG_STREAM_PORT_INTERNAL_BUFFER_CHUNK_TRANSFER_AGAIN_COUNT_LIMIT 5

#define TRC_CFG_STREAM_PORT_RTT_UP_BUFFER_SIZE 8192
#define TRC_CFG_STREAM_PORT_RTT_DOWN_BUFFER_SIZE 32
#define TRC_CFG_STREAM_PORT_RTT_UP_BUFFER_INDEX 1
#define TRC_CFG_STREAM_PORT_RTT_DOWN_BUFFER_INDEX 1
#define TRC_CFG_STREAM_PORT_RTT_MODE SEGGER_RTT_MODE_NO_BLOCK_SKIP
#define TRC_CFG_STREAM_PORT_RTT_NO_LOCK_WRITE 0

#ifdef __cplusplus
}
#endif

#endif /* TRC_STREAM_PORT_CONFIG_H */
