/*
 * Trace Recorder stream port configuration for RX SCI simple-SPI.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef TRC_STREAM_PORT_CONFIG_H
#define TRC_STREAM_PORT_CONFIG_H

#ifdef __cplusplus
extern "C" {
#endif

#define TRC_CFG_STREAM_PORT_USE_INTERNAL_BUFFER 1
#define TRC_CFG_STREAM_PORT_INTERNAL_BUFFER_SIZE (65536u)
#define TRC_CFG_STREAM_PORT_INTERNAL_BUFFER_TRANSFER_MODE TRC_INTERNAL_EVENT_BUFFER_OPTION_TRANSFER_MODE_CHUNKED
#define TRC_CFG_STREAM_PORT_INTERNAL_BUFFER_CHUNK_SIZE (4032u)
#define TRC_CFG_STREAM_PORT_INTERNAL_BUFFER_CHUNK_TRANSFER_AGAIN_SIZE_LIMIT (1008u)
#define TRC_CFG_STREAM_PORT_INTERNAL_BUFFER_CHUNK_TRANSFER_AGAIN_COUNT_LIMIT (16u)

#ifdef __cplusplus
}
#endif

#endif /* TRC_STREAM_PORT_CONFIG_H */
