/*
* Copyright (c) 2016 - 2025 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*/
/***********************************************************************************************************************
*  File Name    : bootloader.c
*  Description  : Main Program
*  Creation Date: 2026-04-12
*  This file was generated by Smart Configurator.
***********************************************************************************************************************/
#include "r_flash_rx_if.h"
#include "rx_bootloader.h"

void main(void);

void main(void)
{
    rx_bootloader_main();
    while (1)
    {
    }
}
