/*
* Copyright (c) 2016 - 2025 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*/
/***********************************************************************************************************************
*  File Name    : aws_wifi_rx671_ek.c
*  Description  : Main Program
*  Creation Date: 2026-06-13
*  This file was generated by Smart Configurator.
***********************************************************************************************************************/
#include "FreeRTOS.h"
#include "task.h"
#include "event_groups.h"
#include "FreeRTOS_IP.h"
#include "FreeRTOS_Sockets.h"
#include "NetworkBufferManagement.h"
#include "iot_logging_task.h"
#include "r_smc_entry.h"
#include "debug_uart.h"
#include "sdio_host.h"
#include "whd_join_config.h"
#include "whd_bringup.h"
#include "aws_iot_mqtt_smoke.h"
#include "rx671_fleet_bootstrap.h"
#include "rx671_fleet_config.h"
#include "tcp_throughput_smoke.h"
#include "demo_config.h"
#include "lfs_common_data.h"
#include "store.h"
#include "mqtt_agent_task.h"
#include "serial.h"
#include "r_sci_rx_pinset.h"
#include "trcRecorder.h"

#if BSP_CFG_CPLUSPLUS == 1
extern void abort(void);
#endif

#define DIAG_PING_TARGET_IP         FreeRTOS_inet_addr_quick(192U, 168U, 10U, 105U)
#define DIAG_PING_PERIOD_TICKS      pdMS_TO_TICKS(5000U)
#define DIAG_PING_PAYLOAD_BYTES     (32U)
#define MAIN_LOGGING_TASK_STACK_SIZE       (configMINIMAL_STACK_SIZE * 6U)
#define MAIN_LOGGING_MESSAGE_QUEUE_LENGTH  (15U)
#define OTA_START_TASK_STACK_SIZE           (configMINIMAL_STACK_SIZE * 2U)
#define OTA_START_TASK_PRIORITY             (tskIDLE_PRIORITY + 1U)
#define OTA_MQTT_AGENT_STACK_SIZE           (6144U)
#define OTA_MQTT_AGENT_PRIORITY             (tskIDLE_PRIORITY + 2U)
#define OTA_PROVISIONER_CLI_STACK_SIZE      (configMINIMAL_STACK_SIZE * 6U)
#define OTA_PROVISIONER_CLI_PRIORITY        (tskIDLE_PRIORITY + 1U)

extern volatile uint32_t g_freertos_tcp_network_up;
extern volatile uint32_t g_whd_port_buffer_max_in_use;
extern volatile uint32_t g_whd_port_buffer_alloc_temp_fail_count;
extern volatile uint32_t g_whd_port_buffer_alloc_perm_fail_count;
extern volatile uint32_t g_whd_port_buffer_wait_loop_count;
extern void UserInitialization(void);
#if (RX671_OTA_RUNTIME_ENABLE == 1)
extern void vStartOtaDemo(void);
#endif
#if (RX671_OTA_PROVISIONER_ENABLE == 1)
extern void CLI_Support_Settings(void);
extern void vRegisterSampleCLICommands(void);
extern void vUARTCommandConsoleStart(uint16_t usStackSize, UBaseType_t uxPriority);
#endif

volatile uint32_t g_logging_task_init_result;
volatile uint32_t g_diag_ping_enable = 0U;
volatile uint32_t g_diag_ping_send_count;
volatile uint32_t g_diag_ping_last_result;
volatile uint32_t g_diag_ping_last_identifier;
volatile uint32_t g_diag_ping_target_ip;
volatile uint32_t g_diag_ping_task_create_result;
volatile uint32_t g_diag_ping_task_enter_count;
volatile uint32_t g_diag_ping_task_loop_count;
volatile uint32_t g_diag_ping_task_condition_count;
volatile uint32_t g_diag_ping_heap_before_create;
volatile uint32_t g_diag_ping_heap_after_create;
EventGroupHandle_t xStartDemoEventGroup = NULL;

#if (RX671_OTA_RUNTIME_ENABLE == 1)
static void ota_log_capacity(void)
{
    char line[192];
    char * p = line;

    p = append_text(p, "[RX671_OTA_CAPACITY] minheap=");
    p = append_dec32(p, (uint32_t)xPortGetMinimumEverFreeHeapSize());
    p = append_text(p, " minnbuf=");
    p = append_dec32(p, (uint32_t)uxGetMinimumFreeNetworkBuffers());
    p = append_text(p, " whdmax=");
    p = append_dec32(p, g_whd_port_buffer_max_in_use);
    p = append_text(p, " tempfail=");
    p = append_dec32(p, g_whd_port_buffer_alloc_temp_fail_count);
    p = append_text(p, " permfail=");
    p = append_dec32(p, g_whd_port_buffer_alloc_perm_fail_count);
    p = append_text(p, " waitloop=");
    p = append_dec32(p, g_whd_port_buffer_wait_loop_count);
    p = append_text(p, "\r\n");
    *p = '\0';
    debug_puts(line);
}
#endif

#if (RX671_OTA_RUNTIME_ENABLE == 1)
static BaseType_t ota_runtime_prepare(void)
{
    if (0 != littlFs_init())
    {
        debug_puts("OTA LittleFS init NG\r\n");
        return pdFAIL;
    }
    if (0 != vprvCacheInit())
    {
        debug_puts("OTA KVS init NG\r\n");
        return pdFAIL;
    }

    if (pdPASS != xMQTTAgentInit())
    {
        debug_puts("OTA MQTT agent init NG\r\n");
        return pdFAIL;
    }
    debug_puts("OTA LittleFS/KVS/MQTT agent init OK\r\n");
    return pdPASS;
}

static void ota_start_task(void * pvParameters)
{
    (void)pvParameters;

    while (pdFALSE == FreeRTOS_IsNetworkUp())
    {
        vTaskDelay(pdMS_TO_TICKS(100U));
    }

    xSetMQTTAgentState(MQTT_AGENT_STATE_INITIALIZED);
    vStartMQTTAgent(OTA_MQTT_AGENT_STACK_SIZE, OTA_MQTT_AGENT_PRIORITY);
    vStartOtaDemo();
    debug_puts("RX671 OTA runtime started\r\n");
    vTaskDelete(NULL);
}
#endif

#if (RX671_OTA_PROVISIONER_ENABLE == 1)
static void ota_provisioner_run(void)
{
    int32_t littlefs_result;
    int32_t kvs_result = -1;

    UserInitialization();
    xStartDemoEventGroup = xEventGroupCreate();
    CLI_Support_Settings();
    /* Pin.c intentionally leaves TXD6 PMR clear until SCI6.TE is enabled.
     * CLI_Support_Settings() opens SCI6 first; route P00 only afterwards. */
    R_SCI_PinSet_SCI6();

    littlefs_result = littlFs_init();
    if (0 == littlefs_result)
    {
        kvs_result = vprvCacheInit();
    }

    vRegisterSampleCLICommands();
    vUARTCommandConsoleStart(OTA_PROVISIONER_CLI_STACK_SIZE,
                             OTA_PROVISIONER_CLI_PRIORITY);
    if ((0 == littlefs_result) && (0 == kvs_result))
    {
        vSerialPutString((const signed char *)
                         "\r\nRX671 OTA provisioner ready: "
                         "LittleFS/KVS OK; use conf set/commit.\r\n",
                         sizeof("\r\nRX671 OTA provisioner ready: "
                                "LittleFS/KVS OK; use conf set/commit.\r\n") - 1U);
    }
    else
    {
        vSerialPutString((const signed char *)
                         "\r\nRX671 OTA provisioner ERROR: "
                         "LittleFS/KVS initialization failed.\r\n",
                         sizeof("\r\nRX671 OTA provisioner ERROR: "
                                "LittleFS/KVS initialization failed.\r\n") - 1U);
    }

    /* SCI6 belongs exclusively to the common CLI in this profile. */
    for (;;)
    {
        vTaskSuspend(NULL);
    }
}
#endif

static bool mac_is_zero(const uint8_t mac[6])
{
    uint32_t i;

    for (i = 0U; i < 6U; i++)
    {
        if (0U != mac[i])
        {
            return false;
        }
    }

    return true;
}

static void diag_ping_task(void * pvParameters)
{
    TickType_t last_wake = xTaskGetTickCount();
    const uint32_t target_ip = DIAG_PING_TARGET_IP;

    (void)pvParameters;
    g_diag_ping_task_enter_count++;
    g_diag_ping_target_ip = target_ip;

    for (;;)
    {
        vTaskDelayUntil(&last_wake, DIAG_PING_PERIOD_TICKS);
        g_diag_ping_task_loop_count++;

        if ((0U != g_diag_ping_enable) && (0U != g_freertos_tcp_network_up))
        {
            BaseType_t ping_id = FreeRTOS_SendPingRequest(target_ip,
                                                          DIAG_PING_PAYLOAD_BYTES,
                                                          pdMS_TO_TICKS(1000U));

            g_diag_ping_task_condition_count++;
            g_diag_ping_send_count++;
            g_diag_ping_last_result = (uint32_t)ping_id;
            if (0 < ping_id)
            {
                g_diag_ping_last_identifier = (uint32_t)ping_id;
            }
        }
    }
}

static void start_freertos_tcp_after_join(void)
{
#if WHD_JOIN_ENABLE
    static const uint8_t fallback_ip[4]      = { 192U, 168U, 10U, 114U };
    static const uint8_t netmask[4]          = { 255U, 255U, 255U, 0U };
    static const uint8_t gateway[4]          = { 192U, 168U, 10U, 1U };
    static const uint8_t dns[4]              = { 192U, 168U, 10U, 1U };
    static const uint8_t local_admin_mac[6]  = { 0x02U, 0x67U, 0x1EU, 0x00U, 0x00U, 0x01U };
    uint8_t mac[6];
    BaseType_t result;

    whd_bringup_get_sta_mac(mac);
    if (mac_is_zero(mac))
    {
        uint32_t i;

        for (i = 0U; i < 6U; i++)
        {
            mac[i] = local_admin_mac[i];
        }
    }

    result = FreeRTOS_IPInit(fallback_ip, netmask, gateway, dns, mac);
    debug_puts((pdPASS == result) ? "FreeRTOS_IPInit OK\r\n" : "FreeRTOS_IPInit NG\r\n");
    if (pdPASS == result)
    {
        g_diag_ping_heap_before_create = xPortGetFreeHeapSize();
        result = xTaskCreate(diag_ping_task, "DIAG_PING", 1024U, NULL, tskIDLE_PRIORITY + 1, NULL);
        g_diag_ping_task_create_result = (uint32_t)result;
        g_diag_ping_heap_after_create = xPortGetFreeHeapSize();
#if (RX671_OTA_RUNTIME_ENABLE == 1)
        result = xTaskCreate(ota_start_task,
                             "OTA_START",
                             OTA_START_TASK_STACK_SIZE,
                             NULL,
                             OTA_START_TASK_PRIORITY,
                             NULL);
        debug_puts((pdPASS == result) ?
                   "OTA start task OK\r\n" :
                   "OTA start task NG\r\n");
#elif (RX671_FLEET_PROVISIONING_ENABLE == 1)
        rx671_fleet_bootstrap_start();
#else
        aws_iot_mqtt_smoke_start();
        tcp_throughput_smoke_start();
#endif
    }
#else
    debug_puts("FreeRTOS+TCP skipped (WHD_JOIN_ENABLE=0)\r\n");
#endif
}

void main_task(void *pvParameters)
{
#if (RX671_OTA_PROVISIONER_ENABLE == 1)
    (void)pvParameters;
    ota_provisioner_run();
#else
    char line[64];
    char * p;
    uint32_t tick = 0U;

    (void)pvParameters;

    (void)xTraceEnable(TRC_START);

    /* Bring up the SCI6 debug console (COM port @ 921600 8N1, P00/P01). */
    debug_uart_init();
    UserInitialization();
    xStartDemoEventGroup = xEventGroupCreate();
    debug_puts("\r\n=== aws_wifi_rx671_ek boot ===\r\n");
    debug_puts("SCI6 debug console up @921600 8N1 (P00=TXD6/P01=RXD6)\r\n");
    g_logging_task_init_result = (uint32_t)xLoggingTaskInitialize(MAIN_LOGGING_TASK_STACK_SIZE,
                                                                  tskIDLE_PRIORITY + 2U,
                                                                  MAIN_LOGGING_MESSAGE_QUEUE_LENGTH);
    debug_puts((pdPASS == (BaseType_t)g_logging_task_init_result) ?
               "FreeRTOS logging task OK\r\n" :
               "FreeRTOS logging task NG\r\n");

#if (RX671_OTA_RUNTIME_ENABLE == 1)
    if (pdPASS != ota_runtime_prepare())
    {
        debug_puts("OTA runtime blocked: persistent credential store unavailable\r\n");
        for (;;)
        {
            vTaskDelay(pdMS_TO_TICKS(1000U));
        }
    }
#endif

#if WHD_BRINGUP_ENABLE
    if (whd_bringup_run())
    {
        start_freertos_tcp_after_join();
    }
    else
    {
        debug_puts("FreeRTOS+TCP skipped (WHD bring-up failed)\r\n");
    }
#else
    /* Issue #30 (b) increment 1+2: SDHI enumerate on the corrected PORTD SDHI
     * pins - CMD0/CMD5 first contact (expect F=2), then CMD3/CMD7 to read the
     * RCA and select the card into the transfer state. */
    {
        uint32_t r4 = 0U;
        uint8_t func = 0U;
        uint16_t rca = 0U;

        if (!sdio_host_init())
        {
            debug_puts("SDHI init NG\r\n");
        }
        else if (!sdio_host_first_contact(&r4, &func))
        {
            debug_puts("CMD5 NG (no card response)\r\n");
        }
        else
        {
            p = line;
            p = append_text(p, "ENUM OK R4=");
            p = append_hex32(p, r4);
            p = append_text(p, " F=");
            p = append_dec32(p, func);
            p = append_text(p, "\r\n");
            *p = '\0';
            debug_puts(line);

            if (!sdio_host_select_card(&rca))
            {
                debug_puts("CMD3/7 NG (select failed)\r\n");
            }
            else
            {
                uint8_t rev = 0U;
                uint8_t cap = 0U;
                uint8_t ready = 0U;

                p = line;
                p = append_text(p, "SEL OK RCA=");
                p = append_hex16(p, rca);
                p = append_text(p, "\r\n");
                *p = '\0';
                debug_puts(line);

                /* Increment 3: open r_sdio_rx over the SDHI CMD52 host, read a
                 * couple of CCCR registers, and enable function 1. */
                if (!sdio_host_protocol_open())
                {
                    debug_puts("R_SDIO_Open NG\r\n");
                }
                else
                {
                    (void)sdio_host_cmd52_read(0U, 0x00U, &rev);   /* CCCR/SDIO revision */
                    (void)sdio_host_cmd52_read(0U, 0x08U, &cap);   /* card capability    */
                    p = line;
                    p = append_text(p, "CCCR rev=");
                    p = append_hex8(p, rev);
                    p = append_text(p, " cap=");
                    p = append_hex8(p, cap);
                    p = append_text(p, "\r\n");
                    *p = '\0';
                    debug_puts(line);

                    if (sdio_host_enable_function(1U, &ready))
                    {
                        uint8_t csr = 0U;
                        uint32_t chipid = 0U;

                        p = line;
                        p = append_text(p, "F1 EN ready=");
                        p = append_hex8(p, ready);
                        p = append_text(p, "\r\n");
                        *p = '\0';
                        debug_puts(line);

                        /* Increment 4a: prepare the CMD53 byte data path (high
                         * speed, 4-bit bus, run clock, F0/F1 block size), bring
                         * up + FORCE the backplane clocks and KSO, then read the
                         * chipcommon chip ID over CMD53. The forced backplane
                         * clocks are what let the data phase run; CHIPID matches
                         * the known-good perf run (chip id low 16 = 0xA9AF). */
                        if (!sdio_host_set_high_speed())
                        {
                            debug_puts("high speed NG\r\n");
                        }
                        if (!sdio_host_set_bus_4bit())
                        {
                            debug_puts("bus 4bit NG\r\n");
                        }
                        if (!sdio_host_set_run_clock())
                        {
                            debug_puts("run clock NG\r\n");
                        }
                        if (!sdio_host_set_block_size())
                        {
                            debug_puts("block size NG\r\n");
                        }
                        if (!sdio_host_request_alp(&csr))
                        {
                            p = line;
                            p = append_text(p, "ALP req NG CSR=");
                            p = append_hex8(p, csr);
                            p = append_text(p, "\r\n");
                            *p = '\0';
                            debug_puts(line);
                        }
                        else
                        {
                            uint8_t slp = 0U;
                            uint8_t clk2 = 0U;
                            bool kso;

                            p = line;
                            p = append_text(p, "ALP CSR=");
                            p = append_hex8(p, csr);
                            p = append_text(p, "\r\n");
                            *p = '\0';
                            debug_puts(line);

                            /* FORCE the backplane clocks (FORCE_ALP + WAKEUPCTRL
                             * + FORCE_HT, no wait for HT_AVAIL). Requesting ALP
                             * alone does not clock the data phase - this is the
                             * precondition the CMD53 read depends on. */
                            {
                                uint8_t fclk = 0U;
                                bool fc = sdio_host_brcm_force_clocks(&fclk);
                                p = line;
                                p = append_text(p, fc ? "FCLK ok csr=" : "FCLK NG csr=");
                                p = append_hex8(p, fclk);
                                p = append_text(p, "\r\n");
                                *p = '\0';
                                debug_puts(line);
                            }

                            /* Keep the WLAN core on (KSO), then snapshot
                             * CHIPCLKCSR/SLEEPCSR right before the read. */
                            kso = sdio_host_request_kso(&slp);
                            (void)sdio_host_cmd52_read(1U, 0x1000eU, &clk2);
                            p = line;
                            p = append_text(p, kso ? "KSO ok slp=" : "KSO NG slp=");
                            p = append_hex8(p, slp);
                            p = append_text(p, " clk=");
                            p = append_hex8(p, clk2);
                            p = append_text(p, "\r\n");
                            *p = '\0';
                            debug_puts(line);

                            if (sdio_host_backplane_read32(0x18000000UL, &chipid))
                            {
                                uint8_t blk[64];

                                p = line;
                                p = append_text(p, "CHIPID=");
                                p = append_hex32(p, chipid);
                                p = append_text(p, "\r\n");
                                *p = '\0';
                                debug_puts(line);

                                /* 64-byte byte-mode CMD53 read (perf B64): the
                                 * first 4 bytes are the chip id again. */
                                if (sdio_host_backplane_read(0x18000000UL, blk, 64U))
                                {
                                    p = line;
                                    p = append_text(p, "B64 ok [0..3]=");
                                    p = append_hex8(p, blk[0]);
                                    p = append_hex8(p, blk[1]);
                                    p = append_hex8(p, blk[2]);
                                    p = append_hex8(p, blk[3]);
                                    p = append_text(p, "\r\n");
                                    *p = '\0';
                                    debug_puts(line);
                                }
                                else
                                {
                                    debug_puts("B64 NG\r\n");
                                }

                                /* CMD53 block-mode read (increment 4b): 1 block
                                 * (F1 block size 64) from chipcommon; first 4
                                 * bytes match the byte read. */
                                if (sdio_host_backplane_read_block(0x18000000UL, blk, 1U))
                                {
                                    p = line;
                                    p = append_text(p, "BLK ok [0..3]=");
                                    p = append_hex8(p, blk[0]);
                                    p = append_hex8(p, blk[1]);
                                    p = append_hex8(p, blk[2]);
                                    p = append_hex8(p, blk[3]);
                                    p = append_text(p, "\r\n");
                                    *p = '\0';
                                    debug_puts(line);
                                }
                                else
                                {
                                    uint8_t bst = 0U;
                                    uint32_t bs2 = 0U;

                                    sdio_host_cmd53_diag(&bst, NULL, &bs2, NULL);
                                    p = line;
                                    p = append_text(p, "BLK NG st=");
                                    p = append_hex8(p, bst);
                                    p = append_text(p, " s2=");
                                    p = append_hex32(p, bs2);
                                    p = append_text(p, "\r\n");
                                    *p = '\0';
                                    debug_puts(line);
                                }

                                /* Increment 4c-1: SOCRAM init (halt the WLAN ARM
                                 * core, reset SOCRAM, prove the data path), then
                                 * a block-mode write/read round-trip to socram -
                                 * validates block write and the firmware-download
                                 * write path before the full download. */
                                if (sdio_host_socram_init())
                                {
                                    uint8_t rd[64];
                                    uint32_t i;
                                    bool match = true;

                                    debug_puts("SOCRAM ok\r\n");

                                    for (i = 0U; i < 64U; i++)
                                    {
                                        blk[i] = (uint8_t)(0x5AU ^ i);
                                    }
                                    if (sdio_host_backplane_write_block(0x00000000UL, blk, 1U) &&
                                        sdio_host_backplane_read_block(0x00000000UL, rd, 1U))
                                    {
                                        for (i = 0U; i < 64U; i++)
                                        {
                                            if (blk[i] != rd[i])
                                            {
                                                match = false;
                                                break;
                                            }
                                        }
                                        debug_puts(match ? "SOCBLK ok\r\n" : "SOCBLK MISMATCH\r\n");
                                    }
                                    else
                                    {
                                        debug_puts("SOCBLK NG\r\n");
                                    }
                                }
                                else
                                {
                                    debug_puts("SOCRAM NG\r\n");
                                }

                                /* Increment 4c-2: full firmware download + boot.
                                 * Stream the blob into SOCRAM, release the WLAN
                                 * ARM core, wait for chip-alive (HT_AVAIL + F2
                                 * ready). FWOK closes the de-risk gate. */
                                {
                                    uint32_t ht_ms = 0U;
                                    uint32_t ior_ms = 0U;

                                    if (sdio_host_fw_download_and_boot(&ht_ms, &ior_ms))
                                    {
                                        p = line;
                                        p = append_text(p, "FWOK ht=");
                                        p = append_dec32(p, ht_ms);
                                        p = append_text(p, "ms ior=");
                                        p = append_dec32(p, ior_ms);
                                        p = append_text(p, "ms\r\n");
                                        *p = '\0';
                                        debug_puts(line);
                                    }
                                    else
                                    {
                                        debug_puts("FW NG\r\n");
                                    }
                                }
                            }
                            else
                            {
                                uint8_t st = 0U;
                                uint32_t s1 = 0U;
                                uint32_t s2 = 0U;
                                uint32_t cr5 = 0U;

                                sdio_host_cmd53_diag(&st, &s1, &s2, &cr5);
                                p = line;
                                p = append_text(p, "CMD53 NG st=");
                                p = append_hex8(p, st);
                                p = append_text(p, " s1=");
                                p = append_hex32(p, s1);
                                p = append_text(p, " s2=");
                                p = append_hex32(p, s2);
                                p = append_text(p, " r5=");
                                p = append_hex32(p, cr5);
                                p = append_text(p, "\r\n");
                                *p = '\0';
                                debug_puts(line);
                            }
                        }
                    }
                    else
                    {
                        debug_puts("F1 enable NG\r\n");
                    }
                }
            }
        }
    }
#endif

    /* Create all other application tasks here */

    /* WAIT_LOOP: 1 Hz heartbeat proves the console + scheduler are alive. */
    while(1) {
        p = line;
        p = append_text(p, "alive tick=");
        p = append_dec32(p, tick);
        p = append_text(p, "\r\n");
        *p = '\0';
        debug_puts(line);

        tick++;
        vTaskDelay(pdMS_TO_TICKS(1000));
    }

    vTaskDelete(NULL);

#endif /* RX671_OTA_PROVISIONER_ENABLE */
}

BaseType_t OtaSelfTest(void)
{
#if (RX671_OTA_RUNTIME_ENABLE == 1)
    /* This runs in the newly activated image before it is accepted.  Keep the
     * existing OTA markers unchanged and add one machine-readable capacity
     * snapshot for the focused hardware gate. */
    ota_log_capacity();
#endif
    return pdTRUE;
}

#if BSP_CFG_CPLUSPLUS == 1
void abort(void)
{

}
#endif
