/*
 * Optional plain TCP throughput smoke test configuration for EK-RX671 Wi-Fi.
 */
#ifndef TCP_THROUGHPUT_CONFIG_H_
#define TCP_THROUGHPUT_CONFIG_H_

#define TCP_THROUGHPUT_MODE_DISABLED    (0U)
#define TCP_THROUGHPUT_MODE_SINK        (1U)  /* RX671 sends to host. */
#define TCP_THROUGHPUT_MODE_SOURCE      (2U)  /* Host sends to RX671. */
#define TCP_THROUGHPUT_MODE_BOTH        (3U)

#ifdef TCP_THROUGHPUT_USE_LOCAL_CONFIG
#include "tcp_throughput_config_local.h"
#endif

#ifndef TCP_THROUGHPUT_ENABLE
#define TCP_THROUGHPUT_ENABLE           (0U)
#endif

#ifndef TCP_THROUGHPUT_MODE
#define TCP_THROUGHPUT_MODE             TCP_THROUGHPUT_MODE_DISABLED
#endif

#ifndef TCP_THROUGHPUT_HOST_IP0
#define TCP_THROUGHPUT_HOST_IP0         (192U)
#endif
#ifndef TCP_THROUGHPUT_HOST_IP1
#define TCP_THROUGHPUT_HOST_IP1         (168U)
#endif
#ifndef TCP_THROUGHPUT_HOST_IP2
#define TCP_THROUGHPUT_HOST_IP2         (10U)
#endif
#ifndef TCP_THROUGHPUT_HOST_IP3
#define TCP_THROUGHPUT_HOST_IP3         (105U)
#endif

#ifndef TCP_THROUGHPUT_PORT
#define TCP_THROUGHPUT_PORT             (5001U)
#endif

#ifndef TCP_THROUGHPUT_TOTAL_BYTES
#define TCP_THROUGHPUT_TOTAL_BYTES      (10485760UL)
#endif

#ifndef TCP_THROUGHPUT_CHUNK_BYTES
#define TCP_THROUGHPUT_CHUNK_BYTES      (1460U)
#endif

#ifndef TCP_THROUGHPUT_TX_CHUNK_BYTES
#define TCP_THROUGHPUT_TX_CHUNK_BYTES   TCP_THROUGHPUT_CHUNK_BYTES
#endif

#ifndef TCP_THROUGHPUT_RX_CHUNK_BYTES
#define TCP_THROUGHPUT_RX_CHUNK_BYTES   TCP_THROUGHPUT_CHUNK_BYTES
#endif

#ifndef TCP_THROUGHPUT_ITERATIONS
#define TCP_THROUGHPUT_ITERATIONS       (1U)
#endif

#ifndef TCP_THROUGHPUT_TASK_STACK_WORDS
#define TCP_THROUGHPUT_TASK_STACK_WORDS (2048U)
#endif

#ifndef TCP_THROUGHPUT_TASK_PRIORITY
#define TCP_THROUGHPUT_TASK_PRIORITY    (tskIDLE_PRIORITY + 2U)
#endif

#ifndef TCP_THROUGHPUT_TIMEOUT_MS
#define TCP_THROUGHPUT_TIMEOUT_MS       (10000U)
#endif

#ifndef TCP_THROUGHPUT_TX_BUFFER_BYTES
#define TCP_THROUGHPUT_TX_BUFFER_BYTES  (65536UL)
#endif

#ifndef TCP_THROUGHPUT_RX_BUFFER_BYTES
#define TCP_THROUGHPUT_RX_BUFFER_BYTES  (65536UL)
#endif

#ifndef TCP_THROUGHPUT_TX_WINDOW_MSS
#define TCP_THROUGHPUT_TX_WINDOW_MSS    (44L)
#endif

#ifndef TCP_THROUGHPUT_RX_WINDOW_MSS
#define TCP_THROUGHPUT_RX_WINDOW_MSS    (44L)
#endif

#ifndef TCP_THROUGHPUT_PROGRESS_BYTES
#define TCP_THROUGHPUT_PROGRESS_BYTES   (0UL)
#endif

#endif /* TCP_THROUGHPUT_CONFIG_H_ */
