param(
    [string]$ProjectRoot = $(Split-Path $PSScriptRoot -Parent),
    [string]$E2Studio = "C:\Renesas\e2_studio_2025_12\eclipse\e2studioc.exe",
    [string]$Workspace = "C:\iotref-rx671-wifi-ws",
    [string]$LogFile = $(Join-Path (Split-Path $PSScriptRoot -Parent) "rx671_wifi_e2studio_build.log"),
    [string]$WifiConfigFile = "",
    [switch]$UseLocalJoinConfig,
    [int]$SoftIrqPollMs = -1
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

$projectRoot = (Resolve-Path -LiteralPath $ProjectRoot).Path
$projectName = "aws_wifi_rx671_ek"
$projectDir = Join-Path $projectRoot "Projects\$projectName\e2studio_ccrx"
$whdDir = Join-Path $projectRoot "Projects\$projectName\external\wifi-host-driver"
$whdPatch = Join-Path $projectRoot "Projects\$projectName\external\patches\whd-v1.70.0-ccrx-portability.patch"
$cproject = Join-Path $projectDir ".cproject"
$localJoinConfig = Join-Path $projectDir "src\whd_join_config_local.h"
$useLocalJoinConfigForBuild = $UseLocalJoinConfig.IsPresent -or (-not [string]::IsNullOrWhiteSpace($WifiConfigFile))

if (-not (Test-Path -LiteralPath $E2Studio)) {
    throw "e2 studio executable not found: $E2Studio"
}

if (-not (Test-Path -LiteralPath (Join-Path $projectDir ".project"))) {
    throw "e2 studio project not found: $projectDir"
}

if (-not (Test-Path -LiteralPath (Join-Path $whdDir ".git"))) {
    throw "WHD submodule is not initialized. Run: git submodule update --init --recursive Projects/aws_wifi_rx671_ek/external/wifi-host-driver"
}

if (-not (Test-Path -LiteralPath $whdPatch)) {
    throw "WHD patch not found: $whdPatch"
}

function Test-GitApply {
    param([string[]]$Arguments)

    & git @Arguments *> $null
    return ($LASTEXITCODE -eq 0)
}

function ConvertTo-CStringLiteral {
    param([string]$Value)

    $builder = [System.Text.StringBuilder]::new()
    foreach ($ch in $Value.ToCharArray()) {
        switch ($ch) {
            "`"" { [void]$builder.Append('\"') }
            "\"  { [void]$builder.Append('\\') }
            "`r" { [void]$builder.Append('\r') }
            "`n" { [void]$builder.Append('\n') }
            "`t" { [void]$builder.Append('\t') }
            default { [void]$builder.Append($ch) }
        }
    }

    return $builder.ToString()
}

function Read-WifiConfig {
    param([string]$Path)

    if (-not (Test-Path -LiteralPath $Path)) {
        throw "Wi-Fi config file not found: $Path"
    }

    $ssid = $null
    $passphrase = $null

    foreach ($line in Get-Content -LiteralPath $Path) {
        $trimmed = $line.Trim()
        if ([string]::IsNullOrWhiteSpace($trimmed) -or $trimmed.StartsWith("#")) {
            continue
        }

        if ($trimmed -match '^(?i:ssid)\s*[:=]\s*(.+)$') {
            $ssid = $Matches[1].Trim().Trim('"')
            continue
        }

        if ($trimmed -match '^(?i:(pass|password|passphrase|psk))\s*[:=]\s*(.+)$') {
            $passphrase = $Matches[2].Trim().Trim('"')
            continue
        }

        if ((-not $ssid) -and (-not $passphrase)) {
            $parts = $trimmed -split '\s+', 2
            if ($parts.Count -ge 2) {
                $ssid = $parts[0].Trim().Trim('"')
                $passphrase = $parts[1].Trim().Trim('"')
            }
        }
    }

    if ([string]::IsNullOrWhiteSpace($ssid) -or [string]::IsNullOrWhiteSpace($passphrase)) {
        throw "Wi-Fi config must contain SSID and passphrase. Supported forms: 'ssid passphrase', 'SSID=...', 'PASS=...'."
    }

    return @{
        Ssid       = $ssid
        Passphrase = $passphrase
    }
}

function Write-LocalJoinConfig {
    param(
        [string]$Path,
        [string]$Ssid,
        [string]$Passphrase,
        [int]$PollMs
    )

    $lines = @(
        "/*",
        " * Generated by tools/build_headless_rx671_wifi.ps1.",
        " * This file contains local AP credentials and is intentionally ignored by git.",
        " */",
        "#ifndef WHD_JOIN_CONFIG_LOCAL_H_",
        "#define WHD_JOIN_CONFIG_LOCAL_H_",
        "",
        "#define WHD_JOIN_ENABLE                (1)",
        "#define WHD_JOIN_SSID                  `"$((ConvertTo-CStringLiteral $Ssid))`"",
        "#define WHD_JOIN_PASSPHRASE            `"$((ConvertTo-CStringLiteral $Passphrase))`""
    )

    if ($PollMs -ge 0) {
        $lines += "#define WHD_SDIO_SOFTIRQ_POLL_MS       (${PollMs}U)"
    }

    $lines += @(
        "",
        "#endif /* WHD_JOIN_CONFIG_LOCAL_H_ */",
        ""
    )

    [System.IO.File]::WriteAllLines($Path, $lines, [System.Text.UTF8Encoding]::new($false))
}

function Add-CProjectDefine {
    param(
        [string]$Text,
        [string]$Define
    )

    $option = "-define=$Define"
    if ($Text.Contains($option)) {
        return $Text
    }

    $needle = '<listOptionValue builtIn="false" value="-define=__FUNCTION__=__func__"/>'
    if (-not $Text.Contains($needle)) {
        throw "Could not find the CCRX userBefore define anchor in .cproject."
    }

    $insert = "$needle`r`n`t`t`t`t`t`t`t`t`t<listOptionValue builtIn=`"false`" value=`"$option`"/>"
    return $Text.Replace($needle, $insert)
}

$reverseCheckArgs = @("-C", $whdDir, "apply", "--reverse", "--check", $whdPatch)
$forwardCheckArgs = @("-C", $whdDir, "apply", "--check", $whdPatch)

if (Test-GitApply $reverseCheckArgs) {
    Write-Host "WHD patch is already applied."
} elseif (Test-GitApply $forwardCheckArgs) {
    Write-Host "Applying WHD patch..."
    & git -C $whdDir apply $whdPatch
    if ($LASTEXITCODE -ne 0) {
        throw "Failed to apply WHD patch."
    }
} else {
    throw "WHD patch state is neither clean nor applied. Check submodule status: $whdDir"
}

if (Test-Path -LiteralPath $Workspace) {
    Remove-Item -LiteralPath $Workspace -Recurse -Force
}

$hardwareDebug = Join-Path $projectDir "HardwareDebug"
if (Test-Path -LiteralPath $hardwareDebug) {
    Remove-Item -LiteralPath $hardwareDebug -Recurse -Force
}

$logFilePath = [System.IO.Path]::GetFullPath($LogFile)
Write-Host "=== RX671 Wi-Fi import + build ==="
Write-Host "Project:   $projectDir"
Write-Host "Workspace: $Workspace"
Write-Host "Log file:  $logFilePath"
if ($useLocalJoinConfigForBuild) {
    Write-Host "Local AP JOIN config: enabled"
}

$cprojectBytes = $null
try {
    if ($useLocalJoinConfigForBuild) {
        if (-not [string]::IsNullOrWhiteSpace($WifiConfigFile)) {
            $wifi = Read-WifiConfig -Path $WifiConfigFile
            Write-LocalJoinConfig -Path $localJoinConfig -Ssid $wifi["Ssid"] -Passphrase $wifi["Passphrase"] -PollMs $SoftIrqPollMs
            Write-Host "Generated ignored local JOIN header: $localJoinConfig"
        } elseif (-not (Test-Path -LiteralPath $localJoinConfig)) {
            throw "Local JOIN config was requested but not found: $localJoinConfig"
        }

        $cprojectBytes = [System.IO.File]::ReadAllBytes($cproject)
        $cprojectText = [System.IO.File]::ReadAllText($cproject)
        $patchedCProject = Add-CProjectDefine -Text $cprojectText -Define "WHD_JOIN_USE_LOCAL_CONFIG"
        [System.IO.File]::WriteAllText($cproject, $patchedCProject, [System.Text.UTF8Encoding]::new($false))
    }

    & $E2Studio `
        -nosplash `
        -application org.eclipse.cdt.managedbuilder.core.headlessbuild `
        -data $Workspace `
        -import $projectDir `
        -cleanBuild "$projectName/HardwareDebug" 2>&1 | Tee-Object -FilePath $logFilePath

    if ($LASTEXITCODE -ne 0) {
        throw "e2 studio build failed with exit code $LASTEXITCODE"
    }
} finally {
    if ($null -ne $cprojectBytes) {
        [System.IO.File]::WriteAllBytes($cproject, $cprojectBytes)
    }
}

foreach ($extension in @(".mot", ".abs", ".x")) {
    $output = Join-Path $hardwareDebug "$projectName$extension"
    if (-not (Test-Path -LiteralPath $output)) {
        throw "Expected build output missing: $output"
    }
}

Write-Host "RX671 Wi-Fi build completed successfully."
