#!/usr/bin/env python3
"""
Render RX72N client credential headers from local PEM files.

This helper keeps secrets out of git while allowing local or CI builds to use
compile-time credentials for automatic pre-provisioning.
"""

from __future__ import annotations

import argparse
from pathlib import Path


HEADER_TEMPLATE = """/*
 * Auto-generated by tools/render_rx72n_client_credentials.py
 * Do not commit secret values.
 */

#ifndef __AWS_CLIENTCREDENTIAL__H__
#define __AWS_CLIENTCREDENTIAL__H__

#define clientcredentialMQTT_BROKER_ENDPOINT         "{endpoint}"
#define clientcredentialIOT_THING_NAME               "{thing_name}"
#define clientcredentialMQTT_BROKER_PORT             (8883)
#define clientcredentialGREENGRASS_DISCOVERY_PORT    (8443)
#define clientcredentialWIFI_SSID                    ""
#define clientcredentialWIFI_PASSWORD                ""
#define clientcredentialWIFI_SECURITY                (eWiFiSecurityWPA2)

#endif /* ifndef __AWS_CLIENTCREDENTIAL__H__ */
"""


KEYS_TEMPLATE = """/*
 * Auto-generated by tools/render_rx72n_client_credentials.py
 * Do not commit secret values.
 */

#ifndef AWS_CLIENT_CREDENTIAL_KEYS_H
#define AWS_CLIENT_CREDENTIAL_KEYS_H

#define keyCLIENT_CERTIFICATE_PEM                   \\
{certificate}

#define keyJITR_DEVICE_CERTIFICATE_AUTHORITY_PEM    (NULL)

#define keyCLIENT_PRIVATE_KEY_PEM                   \\
{private_key}

#endif /* AWS_CLIENT_CREDENTIAL_KEYS_H */
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Render RX72N client credential headers")
    parser.add_argument("--thing-name", required=True, help="AWS IoT Thing name")
    parser.add_argument("--endpoint", required=True, help="AWS IoT endpoint")
    parser.add_argument("--cert", required=True, type=Path, help="Client certificate PEM")
    parser.add_argument("--key", required=True, type=Path, help="Client private key PEM")
    parser.add_argument("--credential-header", required=True, type=Path, help="Output aws_clientcredential.h path")
    parser.add_argument("--keys-header", required=True, type=Path, help="Output aws_clientcredential_keys.h path")
    return parser.parse_args()


def read_pem(path: Path) -> str:
    text = path.read_text(encoding="utf-8")
    return text.replace("\r\n", "\n").replace("\r", "\n").strip("\n")


def to_c_multiline_string(text: str) -> str:
    lines = text.split("\n")
    rendered = []
    for line in lines:
        rendered.append(f'    "{line}\\n" \\')
    if rendered:
        rendered[-1] = rendered[-1].rstrip(" \\")
    return "\n".join(rendered)


def main() -> int:
    args = parse_args()

    cert_pem = read_pem(args.cert)
    key_pem = read_pem(args.key)

    args.credential_header.parent.mkdir(parents=True, exist_ok=True)
    args.keys_header.parent.mkdir(parents=True, exist_ok=True)

    args.credential_header.write_text(
        HEADER_TEMPLATE.format(
            endpoint=args.endpoint,
            thing_name=args.thing_name,
        ),
        encoding="utf-8",
        newline="\n",
    )

    args.keys_header.write_text(
        KEYS_TEMPLATE.format(
            certificate=to_c_multiline_string(cert_pem),
            private_key=to_c_multiline_string(key_pem),
        ),
        encoding="utf-8",
        newline="\n",
    )

    print("Rendered client credential headers")
    print(f"  header: {args.credential_header}")
    print(f"  keys:   {args.keys_header}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
